<h1>Connexion</h1>

<?php if ($errors->hasErrors()): ?>
    <aside class="alert alert-danger">
        <ul>
            <?php foreach ($errors->all() as $index => $error): ?>
                <li><?= $errors->get($index) ?></li>
            <?php endforeach ?>
        </ul>
    </aside>
<?php endif ?>

<form method="post">
    <div class="form-group">
        <label for="username">Nom d'utilisateur</label>
        <input type="text" name="username" id="username" class="form-control">
    </div>
    <div class="form-group">
        <label for="password">Mot de passe</label>
        <input type="password" name="password" id="password" class="form-control">
    </div>
    <div class="mt-2">
        <button class="btn btn-primary">Se connecter</button>
    </div>
</form>