<h1>Inscription</h1>

<form method="post">
    <div class="form-group">
        <label for="username">Nom d'utilisateur</label>
        <input type="text" class="form-control <?= $errors->has('username') ? 'is-invalid' : '' ?>" name="username" id="username" required>
        <div class="invalid-feedback">
            <?= $errors->get('username') ?>
        </div>
    </div>
    <div class="form-group">
        <label for="password">Mot de passe</label>
        <input minlength="6" type="password" name="password" id="password" class="form-control" required>
    </div>
    <div class="mt-2">
        <button class="btn btn-primary">S'inscrire</button>
    </div>
</form>