<div class="event-list">
    <h1>Liste des évenements</h1>
    <?php foreach($events as $event) : ?>   

        <h2><a href="<?= url("/event?id=" . $event['id'])  ?>"><?= htmlspecialchars($event['title']) ?></a></h2>
        <img src="../<?= htmlspecialchars($event['pictures']) ?>" class="col-6" alt="">
        <p><?= htmlspecialchars($event['description']) ?></p>
        <sub>crée le : <?= htmlspecialchars($event['created_at']) ?> par <?= htmlspecialchars($event['username']) ?></sub>

    <?php endforeach ?>
</div>