<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog V3</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="<?= url('/') ?>">Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="<?= url('/') ?>">Accueil</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= url('/events') ?>">Liste des événements</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= url('/admin') ?>">Administration</a>
                            </li>
                        <?php if ($user->isAuthenticated()): ?>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= url('/register') ?>">Inscription</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= url('/login') ?>">Connexion</a>
                            </li>
                        <?php else : ?>                                    
                            <li class="nav-item">
                                <a class="nav-link" href="<?= url('/logout') ?>">Déconnexion</a>
                            </li>
                        <?php endif ?>
                    </ul>
                    <span class="navbar-text">
                        <?php if ($user->isAuthenticated()): ?>
                            Bonjour <?= $user->getUsername() ?>
                        <?php else: ?>
                            <a href="<?= url('/login') ?>">Se connecter</a>
                        <?php endif ?>
                    </span>
                </div>
            </div>
        </nav>
    </header>
    <main class="container my-2">
        <?php require $template ?>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>