<h1>Event</h1>

<article class="border-bottom py-3 mb-2">
    <header class="my-2">
        <a href="<?= url("/edit?id=".$_GET['id']) ?>">edit</a>
        <h2><?= htmlspecialchars($event['title']) ?></h2>
        <small>Rédigé par <?= htmlspecialchars($event['username']) ?> le <?= htmlspecialchars($event['created_at']) ?></small>
    </header>
    <h3><?= htmlspecialchars($event['started_at']) ?></h3>
    <p><?= htmlspecialchars($event['description']) ?></p>
</article>