<div class="row justify-content-between">
    <h1 class='col-8'>Event</h1>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary col-2 align-self-center me-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Je participe
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Êtes vous sur de vouloir participer ? 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Non</button>
                <a href="<?= url("/event/registration"."?id=".$event['id']) ?>" ><button class="btn btn-success">Oui</button></a>
            </div>
            </div>
        </div>
    </div>
    
</div>

<article class="border-bottom py-3 mb-2">
    <div class="row justify-content-center">
        <header class="my-2">
            <?php if ($user->getUsername() === 'admin' || $user->getId() === $event['user_id']): ?>
            <a href="<?= url("/edit?id=".$_GET['id']) ?>">edit</a>
            <?php endif ?>
            <h2><?= htmlspecialchars($event['title']) ?></h2>
            <small>Rédigé par <?= htmlspecialchars($event['username']) ?> le <?= htmlspecialchars($event['created_at']) ?></small>
        </header>
            <img src="../<?= htmlspecialchars($event['pictures']) ?>" class="col-6" alt="">

            <div class="row">
                <p><?= htmlspecialchars($event['description']) ?></p>
                <p>Début de l'événement <?= htmlspecialchars($event['started_at']) ?></p>
            </div>
    </div>
</article>

<section>
    <h2>Espace commentaires</h2>
    
    <?php if($user->isAuthenticated()): ?> 
    <form method="post">
        <fieldset>
            <input type="hidden" name="event_id" value="<?= $event['id'] ?>">
            <legend>Ajouter un commentaire</legend>
            <div class="form-group">
                <label for="content">Commentaire</label>
                <textarea name="content" id="content" cols="30" rows="10" class="form-control"></textarea>
            </div>
            <div class="mt-2">
                <button class="btn btn-primary" formaction="<?= url('/event/comment') ?>">Ajouter</button>
            </div>
        </fieldset>
    </form>
    <?php endif ?>
    
    <ul class="list-unstyled border-top py-2 my-2">
        <?php foreach ($comments as $comment): ?>
            <li class="mb-3">
                <article>
                    <header>
                        <small>Rédigé le <?= $comment['created_at'] ?> par <?= $comment['username'] ?></small>
                    </header>
                    <?= htmlspecialchars($comment['content']) ?>
                </article>
            </li>
        <?php endforeach ?>
    </ul>
</section>

<?php 

?>