<h1>Création d'un nouvel événement</h1>

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="title">Titre</label>
        <input type="text" name="title" id="title" class="form-control">
    </div>
    <div class="form-group">
        <label for="description">Contenu</label>
        <textarea name="description" id="description" class="form-control" cols="30" rows="10"></textarea>
    </div>
    <div class="form-group">
        <label for="category">Catégorie</label>
        <select name="category" id="category" class="form-control">
            <?php foreach ($categories as $category): ?>
                <option value="<?= $category['id'] ?>"><?= ucfirst($category['name']) ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div class="form-group">
        <label for="picture">Votre fichier</label>
        <input type="file" name="picture" id="picture" multiple class="form-control">
    </div>
    <div class="form-group">
        <label for="position">Position</label>
        <input type="text" name="position" id="position" class="form-control">
    <div class="form-group">
        <label for="date">Date</label>
        <input type="datetime-local" name="date" id="date" class="form-control">
    </div>   
    <div class="mt-2">
        <button class="btn btn-primary">Ajouter</button>
    </div>
</form>