<article class="border-bottom py-3 mb-2">
    <header class="my-2">
        <h1><?= htmlspecialchars($event['title']) ?></h1>
        <small>Rédigé par <?= htmlspecialchars($event['username']) ?> le <?= $event['created_at'] ?></small>
    </header>
    <?= nl2br(htmlspecialchars($event['description'])) ?>
</article>

<section>
    <h2>Espace commentaires</h2>
    <form method="post" action="<?= url('/events/comment') ?>">
        <fieldset>
            <input type="hidden" name="event_id" value="<?= $event['id'] ?>">
            <legend>Ajouter un commentaire</legend>
            <div class="form-group">
                <label for="nickname">Pseudo</label>
                <input type="text" name="nickname" class="form-control" id="nickname">
            </div>
            <div class="form-group">
                <label for="content">Commentaire</label>
                <textarea name="content" id="content" cols="30" rows="10" class="form-control"></textarea>
            </div>
            <div class="mt-2">
                <button class="btn btn-primary">Ajouter</button>
            </div>
        </fieldset>
    </form>
    
    <ul class="list-unstyled border-top py-2 my-2">
        <?php foreach ($comments as $comment): ?>
            <li class="mb-3">
                <article>
                    <header>
                        <small>Rédigé par <?= htmlspecialchars($comment['nickname']) ?> le <?= $comment['created_at'] ?></small>
                    </header>
                    <?= htmlspecialchars($comment['content']) ?>
                </article>
            </li>
        <?php endforeach ?>
    </ul>
</section>